---

- name: Clone application from git
  git:
    dest=/tmp/beertropolis
    repo=https://github.com/Javi-Rev/Beertropolis
    version=aws
  
- name: Install bundler
  gem:
    name=bundler
    state=present
  
- name: Bundler Install
  bundler:
    chdir=/tmp/beertropolis
    executable=~/bin/bundler
    state=present
    gemfile=Gemfile

- name: Create DB
  command: >
    chdir=/tmp/beertropolis
    /home/ec2-user/bin/bundle exec rake db:create
  
- name: Migrate DB
  command: >
    chdir=/tmp/beertropolis
    /home/ec2-user/bin/bundle exec rake db:migrate
    
- name: Seed DB
  command: >
    chdir=/tmp/beertropolis
    /home/ec2-user/bin/bundle exec rake db:seed

- name: Start Rails Server
  command: >
    chdir=/tmp/beertropolis
    pumactl --config-file puma_config.rb start

