---

- name: Configure Server with Ruby
  hosts: all
  remote_user: ec2-user
  sudo: yes
  roles:
    - ruby

- name: Install Rails Application
  hosts: all
  remote_user: ec2-user
  sudo: no
  roles:
    - app
  environment:
    RAILS_ENV: production
    PATH: "/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/aws/bin:/home/ec2-user/.local/bin:/home/ec2-user/bin"
    TWITTER_CONSUMER_KEY: "{{ lookup('env', 'TWITTER_CONSUMER_KEY') }}"
    TWITTER_CONSUMER_SECRET: "{{ lookup('env', 'TWITTER_CONSUMER_SECRET') }}"
    SECRET_KEY_BASE: "{{ lookup('env', 'SECRET_KEY_BASE') }}"
